from typing import Protocol
from src.repositories.models import (
    TweetThreadCreate,
    TweetThreadResponse,
    TweetCreate,
    TweetRead,
)
from src.types import Embedding


class TweetThreadRepositoryInterface(Protocol):
    def add(self, thread: TweetThreadCreate) -> TweetThreadResponse: ...

    def get(self, thread_id: int) -> TweetThreadResponse | None: ...

    def get_by_root_tweet_id(self, root_tweet_id: str) -> TweetThreadResponse | None: ...

    def get_by_ids(self, thread_ids: list[int]) -> list[TweetThreadResponse]: ...

    def list_threads(self) -> list[TweetThreadResponse]: ...

    def update_tweet_count(self, thread_id: int, tweet_count: int) -> None: ...

    def delete(self, thread_id: int) -> None: ...


class TweetRepositoryInterface(Protocol):
    def add(self, tweet: TweetCreate) -> TweetRead: ...

    def get(self, tweet_id: int, thread_id: int) -> TweetRead | None: ...

    def get_by_id(self, tweet_id: int) -> TweetRead | None: ...

    def get_by_tweet_id(self, tweet_id: str) -> TweetRead | None: ...

    def get_random(self) -> TweetRead | None: ...

    def get_by_thread_id(self, thread_id: int) -> list[TweetRead]: ...

    def find_similar_tweets(self, tweet: TweetRead, limit: int = 5) -> list[TweetRead]: ...

    def search_tweets_by_embedding(
        self, embedding: Embedding, limit: int = 10, similarity_threshold: float = 0.5
    ) -> list[TweetRead]: ...

    def get_tweet_counts_by_thread_ids(self, thread_ids: list[int]) -> dict[int, int]: ...

    def count_with_embeddings(self) -> int: ...
