"""Unique constraint

Revision ID: 68d8c251ac25
Revises: 75aecc755453
Create Date: 2025-06-01 22:04:00.584656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '68d8c251ac25'
down_revision: Union[str, None] = '75aecc755453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_title_author', 'book', ['title', 'author'])
    op.add_column('note', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint('uix_content_hash', 'note', ['content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_content_hash', 'note', type_='unique')
    op.drop_column('note', 'content_hash')
    op.drop_constraint('uix_title_author', 'book', type_='unique')
    # ### end Alembic commands ###
