"""created_at

Revision ID: 733289f694be
Revises: 68d8c251ac25
Create Date: 2025-06-07 23:13:29.235485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733289f694be'
down_revision: Union[str, None] = '68d8c251ac25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('note', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'created_at')
    op.drop_column('book', 'created_at')
    # ### end Alembic commands ###
