from typing import Protocol
from src.repositories.models import BookCreate, BookRead, Note, Evaluation
from src.types import Embedding


class BookRepositoryInterface(Protocol):
    def add(self, book: BookCreate) -> BookRead: ...

    def get(self, book_id: int) -> BookRead | None: ...

    def list_books(self) -> list[BookRead]: ...

    def get_by_ids(self, book_ids: list[int]) -> list[BookRead]: ...

    def delete(self, book_id: int) -> None: ...


class NoteRepositoryInterface(Protocol):
    def add(self, note: Note) -> Note: ...

    def get(self, note_id: int) -> Note | None: ...

    def list_notes(self) -> list[Note]: ...

    def delete(self, note_id: int) -> None: ...

    def get_random(self) -> Note | None: ...

    def update_embedding(self, note: Note, embedding: Embedding) -> Note: ...

    def get_by_book_id(self, book_id: int) -> list[Note]: ...

    def find_similar_notes(self, note: Note, limit: int = 5) -> list[Note]: ...

    def search_notes_by_embedding(
        self, embedding: Embedding, limit: int = 10, similarity_threshold: float = 0.5
    ) -> list[Note]: ...

    def get_note_counts_by_book_ids(self, book_ids: list[int]) -> dict[int, int]: ...


class EvaluationRepositoryInterface(Protocol):
    def add(self, evaluation: Evaluation) -> Evaluation: ...

    def get_by_note_id(self, note_id: int) -> list[Evaluation]: ...
