from typing import Protocol
from src.repositories.models import Book, Note


class BookRepositoryInterface(Protocol):
    def add(self, book: Book) -> Book: ...

    def get(self, book_id: int) -> Book | None: ...

    def list_books(self) -> list[Book]: ...

    def delete(self, book_id: int) -> None: ...


class NoteRepositoryInterface(Protocol):
    def add(self, note: Note) -> Note: ...

    def get(self, note_id: int) -> Note | None: ...

    def list_notes(self) -> list[Note]: ...

    def delete(self, note_id: int) -> None: ...

    def get_random(self) -> Note | None: ...
