"""
Centralized prompt templates and system instructions for LLM interactions.

This module contains all prompt templates, system instructions, and prompt-related
utilities used throughout the application.
"""

# System instructions for different LLM roles
SYSTEM_INSTRUCTIONS = {
    "evaluator": "You are an expert evaluator of AI responses. Provide objective, constructive evaluations.",
    "context_provider": "You are helping a user remember the concept highlighted in a given book. Please provide some additional context and use some examples so that it will be easier for the user to understand it more.",
}


def create_evaluation_prompt(original_prompt: str, llm_response: str) -> str:
    """
    Create a prompt for evaluating LLM response quality.

    Args:
        original_prompt: The original prompt that was sent to the LLM
        llm_response: The response generated by the LLM

    Returns:
        A formatted evaluation prompt string
    """
    return f"""Please evaluate the following LLM response based on the original prompt. 

Original Prompt:
{original_prompt}

LLM Response:
{llm_response}

Please evaluate this response on the following criteria:
1. Relevance: How well does the response address the prompt?
2. Accuracy: Is the information provided correct and factual?
3. Helpfulness: Does the response provide useful information?
4. Clarity: Is the response clear and well-structured?

Provide a score from 0.0 to 1.0 (where 1.0 is perfect) and a brief explanation of your evaluation.

Format your response as:
Score: [0.0-1.0]
Evaluation: [Your detailed evaluation]"""


def create_context_prompt(book_title: str, note_content: str) -> str:
    """
    Create a prompt for generating additional context for a note.

    Args:
        book_title: The title of the book the note is from
        note_content: The content of the note

    Returns:
        A formatted context generation prompt string
    """
    return f"Based on the following notes from the notebook titled '{book_title}': {note_content}, can you provide additional context or insights?"
