"""
Centralized prompt templates and system instructions for LLM interactions.

This module contains all prompt templates, system instructions, and prompt-related
utilities used throughout the application.
"""

# System instructions for different LLM roles
SYSTEM_INSTRUCTIONS = {
    "evaluator": "You are an expert evaluator of AI responses. Provide objective, constructive evaluations.",
    "context_provider": """You are a learning assistant helping readers deepen their understanding of highlighted book passages.

Your role is to:
- Explain the key concept in 2-3 concise sentences
- Provide 2-3 concrete real-world examples or analogies
- Connect the idea to broader themes when relevant

Keep responses focused, practical, and under 200 words.

Format your response in markdown:
- **Key Concept:** [2-3 sentence explanation]
- **Examples:** [2-3 concrete real-world examples or analogies, as a bulleted list]
- **Connection:** [Optional: Broader theme links]""",
}


def create_evaluation_prompt(original_prompt: str, llm_response: str) -> str:
    """
    Create a prompt for evaluating LLM response quality.

    Args:
        original_prompt: The original prompt that was sent to the LLM
        llm_response: The response generated by the LLM

    Returns:
        A formatted evaluation prompt string
    """
    return f"""Please evaluate the following LLM response based on the original prompt. 

Original Prompt:
{original_prompt}

LLM Response:
{llm_response}

Please evaluate this response on the following criteria:
1. Relevance: How well does the response address the prompt?
2. Accuracy: Is the information provided correct and factual?
3. Helpfulness: Does the response provide useful information?
4. Clarity: Is the response clear and well-structured?

Provide a score from 0.0 to 1.0 (where 1.0 is perfect) and a brief explanation of your evaluation.

Format your response as:
Score: [0.0-1.0]
Evaluation: [Your detailed evaluation]"""


def create_context_prompt(book_title: str, note_content: str) -> str:
    """
    Create a prompt for generating additional context for a note.

    Args:
        book_title: The title of the book the note is from
        note_content: The content of the note

    Returns:
        A formatted context generation prompt string
    """
    return f"""Book: "{book_title}"

Highlighted passage:
"{note_content}"

Explain this concept clearly and provide a practical example that makes it memorable."""
