from typing import Protocol
from src.repositories.models import URLCreate, URLResponse, URLChunkCreate, URLChunkRead
from src.types import Embedding


class URLRepositoryInterface(Protocol):
    def add(self, url: URLCreate) -> URLResponse: ...

    def get(self, url_id: int) -> URLResponse | None: ...

    def get_by_url(self, url: str) -> URLResponse | None: ...

    def get_by_ids(self, url_ids: list[int]) -> list[URLResponse]: ...

    def list_urls(self) -> list[URLResponse]: ...

    def delete(self, url_id: int) -> None: ...


class URLChunkRepositoryInterface(Protocol):
    def add(self, chunk: URLChunkCreate) -> URLChunkRead: ...

    def get(self, chunk_id: int, url_id: int) -> URLChunkRead | None: ...

    def get_by_id(self, chunk_id: int) -> URLChunkRead | None: ...

    def get_random(self) -> URLChunkRead | None: ...

    def get_by_url_id(self, url_id: int) -> list[URLChunkRead]: ...

    def find_similar_chunks(
        self, chunk: URLChunkRead, limit: int = 5
    ) -> list[URLChunkRead]: ...

    def search_chunks_by_embedding(
        self, embedding: Embedding, limit: int = 10, similarity_threshold: float = 0.5
    ) -> list[URLChunkRead]: ...

    def get_chunk_counts_by_url_ids(self, url_ids: list[int]) -> dict[int, int]: ...

    def count_with_embeddings(self) -> int: ...

    def delete_by_url_id(self, url_id: int) -> None: ...
