name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.17"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked

      - name: Run ruff
        run: uv run ruff check

      - name: Run pyright
        run: uv run pyright

      - name: Run pytest
        run: uv run pytest
